version: '2'
services:
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php72
      # nginx镜像的路径
    image: nginx:latest
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
    volumes:
      #- ./nginx/www:/usr/share/nginx/html
      - ./conf/nginx/:/etc/nginx/
      - ./log/nginx/:/var/log/nginx/
        # nginx意外退出时自动重启
    restart: always
        # 映射80和443端口
    ports:
      - "80:80"
      #- "443:443"

        # 容器名称
    container_name: nginx

  php72:
    depends_on:
      - mysql
    build: ./images/php/
    ports:
      - "9009"      
    #volumes:
      #- ./conf/php-fpm/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
     # - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
     # - ./conf/php/php.ini:/usr/local/php/etc/php.ini
     # - ./log/php-fpm/php-fpm.log:/usr/local/php/var/log/php-fpm.log
     # - ./www:/usr/share/nginx/html
    restart: always
    container_name: php

  # MySQL
  mysql:
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: mysql

