version "1"
services:
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
        #- "443:443"
      volumes:
        # app
        - ./www:/usr/share/nginx/html
        # nginx configs
        #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        #- ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        # certificates
        #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
        #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      links:
        - php72:__DOCKER_PHP_FPM__
    
    php72:
      depends_on:
        - mysql
      build: ./images/php/
      ports:
        - "9009"
      volumes:
        #- ./app/src:/usr/share/nginx/html
        # Your php.ini
        - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
      # environment:
        # Set your APP env variables here:
        # - APP_KEY=
        # - DB_HOST=
        # - DB_DATABASE=
        # - DB_USERNAME=
        # - DB_PASSWORD=
      links:
        - mysql:mysql
      container_name: php72
    
    # database
    mysql:
      image: mysql:latest
      ports:
        # Allow client to access 3306
        - "3309:3309"
      volumes:
        # NOTE: your data will be stored in ./mysql
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
